import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta httpEquiv="X-UA-Compatible" content="ie=edge" />
        <title>Raiiar - Tick-Tac-Toe</title>
        <link rel="stylesheet" href="style.css" />
      </Head>
            <iframe src="https://www.raiiar.com.ng/ox" frameBorder="0" scrolling="no" width="100%" height="540px" />
      <footer id="footer">
      <a href="http://www.raiiar.com.ng">
      <font size="4" color="GREEN">
      Raiiar - Tic-Tac-Toe &copy; <strong>It_Ddd - App Development - Another website designed by Julius Olatokunbo&nbsp;</strong></font>
      </a>
      </footer>
      <Script
        src="../styles/app.js"
        strategy="afterInteractive"
      />

    </div>
  )
}
